<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.13" />
  <xacro:property name="wheel_length" value="0.08" />
  <xacro:property name="box_x" value="0.4" />
  <xacro:property name="box_y" value="0.2" />
  <xacro:property name="box_z" value="0.1" />
  <xacro:property name="caster_radius" value="${wheel_radius/2}"/>
  <xacro:property name="distance_wheels" value="${box_y+wheel_length+0.1}" />
  <!--
  <xacro:property name="distance_wheels" value="0.4" />
  -->
  <xacro:property name="offset_collision" value="0.005" />
  <xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
 <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

 <material name="green">
    <color rgba="0 0.5 0 1"/>
  </material>

<!-- CHASSIS -->
  <link name="robot_footprint">
    <pose>0 0 0 0 0 0</pose>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>  
      <material name="red"/>
    </visual>
  </link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <link name="chassis">
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="5.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name="collision_box">
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="${box_x} ${box_y} ${box_z}"/>
      </geometry>
    </collision>

    <visual name="visual_box">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${box_x} ${box_y} ${box_z}"/>
      </geometry>
      <material name="blue"/>
    </visual>

        <visual name="control_box">
      <origin xyz="-0.1 0 ${box_z}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${box_y/2+0.05}" length="0.2"/>
      </geometry>
      <material name="white"/>
    </visual>

    <visual name="back_caster_visual">
      <origin xyz="-0.15 0 -0.05" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision name="back_caster_collision">
      <origin xyz="-0.15 0 -0.05" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.0499"/>
      </geometry>
    </collision>

    <visual name="front_caster_visual">
      <origin xyz="0.15 0 ${-caster_radius}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
       <material name="blue"/>
    </visual>

    <collision name="front_caster_collision">
      <origin xyz="0.15 0 ${-caster_radius}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>

  </link>

<!-- WHEELS -->

   <link name ="left_wheel">
    <pose>0 0 0 0 0 0</pose>
    <visual name='left_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
    <mass value="5.0"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>
    <collision name="left_wheel_collision">
        <origin xyz="0 0 0" rpy="0 ${radians(90)} ${radians(90)}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length - offset_collision}"/>
        </geometry>
    </collision>>
  </link>


 <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="-0.15 ${distance_wheels/2} 0.0" rpy="0 0 0"/>
    <child link="left_wheel"/>
    <parent link="robot_footprint"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="0.1"/>
  </joint>



   <link name ="right_wheel">
    <pose>0 0 0 0 0 0</pose>
    <visual name='right_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <inertial>
    <mass value="5.0"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>
    <collision name="right_wheel_collision">
      <origin xyz="0 0 0" rpy="0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length- offset_collision}"/>
      </geometry>
    </collision>>
  </link>

  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="-0.15 -${distance_wheels/2} 0.0" rpy="0 0 0"/>
    <child link="right_wheel"/>
    <parent link="robot_footprint"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="0.1"/>
  </joint>

<!-- SENSORS -->

  <link name="camera">
  <pose>0 0 0 0 0 0</pose>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="0.1"/>
      <inertia  ixx="1e-6" ixy="0.0" ixz="0.0" 
                iyy="1e-6" iyz="0.0" 
                izz="1e-6"/>
    </inertial>
    <visual name="camera_visual">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.2 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <parent link="robot_footprint"/>
    <child link="camera"/>
    <axis xyz="0.0 1 0.0"/>
  </joint>

  <link name="hokuyo">
  <pose> 0 0 0 0 0 0 </pose>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="1.0e-5"/>
      <inertia  ixx="1e-6" ixy="0.0" ixz="0.0" 
                iyy="1e-6" iyz="0.0" 
                izz="1e-6"/>
    </inertial>
    <visual name="hokuyo_visual">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="0.15 0.0 0.1" rpy="0.0 0.0 0.0"/>
    <parent link="robot_footprint"/>
    <child link="hokuyo"/>
    <axis xyz="0.0 1.0 0.0"/>
  </joint>


</robot>